### ISSUE TITLE
Does Microsoft.Azure.StackExchangeRedis depend on System.Runtime, Version=6.0.0.0?

### ISSUE THREAD

**Issue by jinhao1994** [Azure/Microsoft.Azure.StackExchangeRedis#41]
I'm seeing the error Assembly 'Microsoft.Azure.StackExchangeRedis' with identity 'Microsoft.Azure.StackExchangeRedis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' when onboarding Microsoft.Azure.StackExchangeRedis. But it looks like the latest System.Runtime is 4.3.1. How should I fix this?

**Comment by philon-msft** [comment]
It sounds like your application targets the .NET Framework, but somehow it was picking up the net6.0 version of this package assembly rather than the netstandard2.0 version. There are some suggestions here for how to resolve such a mismatch: https://stackoverflow.com/questions/72708115/unity-error-cs1705-which-has-a-higher-version-than-referenced-assembly
